// wx-taroapp/src/app.jsx
import { Component } from 'react'
import { Provider } from 'mobx-react'
import './app.scss'
import Taro from '@tarojs/taro'

import store from './store'

export default class App extends Component {
  onLaunch() {
    console.log('启动了')
    Taro.login().then(res=>{
      console.log('code', res)
      // Taro.request().then()
    })
  }
  render() {
    let { props } = this
    return (
      <Provider {...store}>
        {props.children}
      </Provider>
    )
  }
}

// project-uniapp/App.vue
<script>
	export default {
		onLaunch: function() {
			console.log('App Launch', '启动了')

			// #ifndef MP-WEIXIN
			// uni.login({
			// 	success(res) {
			// 		console.log('code', res)
			// 	}
			// })
			// #endif
		},
		onShow: function() {
			console.log('App Show')
		},
		onHide: function() {
			console.log('App Hide')
		}
	}
</script>

<style>
	/*每个页面公共css */
</style>
